version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_password
    volumes:
      - chat-live-mysql-data:/var/lib/mysql
    networks:
      - chat-live-network 
    command: --bind-address=0.0.0.0
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks: 
      - chat-live-network
  
  backend:
    image: backend
    restart: always
    build:
      context: .
      dockerfile: ChatLive/Dockerfile
    depends_on:
      - mysql
    networks:
      - chat-live-network
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=chat_live_db;User=root;Password=admin_password;"
      
    ports:
      - "8080"
  
  frontend:
    image: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - backend
    networks:
      - chat-live-network
      
volumes: 
  chat-live-mysql-data: 

networks:
  chat-live-network:
    driver: bridge